### ISSUE TITLE
开源点赞！

### ISSUE THREAD

**Issue by Shaunwei** [yuadsl3010/Delete-So#1]
需要改进什么的话， 把要求可以放到issue里面， 这样会有更多的人来帮忙！

**Comment by yuadsl3010** [comment]
目前的代码是分两部分：
1、爬虫，这个貌似只能解决一下BUG；
2、网站源码，我最近要离职了，时间比较多，准备把架构放到django上面去，目前开了个头；

issue我会用起来的

**Comment by Shaunwei** [comment]
okay, 需要帮忙的话，就写在issue上吧。
