### ISSUE TITLE
几点疑问

### ISSUE THREAD

**Issue by blackbbc** [yuadsl3010/Delete-So#14]
看了源代码表示算法很蛋疼啊。。。
首先是类型未知，标题不详，UP主不详。。
为什么不能进www.acfun.tv/acxxxxxx这个详细页面去扒呢
然后看了下扒评论的算法 貌似只扒第一页评论 这样真的好吗。。。
最后 数据库貌似可以注入。。

**Comment by yuadsl3010** [comment]
1.那些未知什么的，进页面再去爬实在太耗带宽了
2.A站的评论每一页都显示50条，加上这50条的评论，通常在250左右，如果我从一开始就抓取，那么只有极少的评论会漏掉，换取更快的速度
3.SQL注入的话没有研究，找时间换成statement之类的应该会好一点（这个我清理完留言板就做）

**Comment by blackbbc** [comment]
唔 我自己使用pyspider写了一个爬虫
不知道效率会怎么样 总之修改了很多bug 以及会一页页的翻评论
放在了sweetll.me:8000上面
源码在https://github.com/blackbbc/Acfun-Deleted-Comments 上
我先爬个几天 如果还行的话 希望能够与您合作 : )
