### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by yuadsl3010** [yuadsl3010/Delete-So#2]
1、爬虫抓取图片的功能还有待实现

已完成：
1、评论系统不支持过滤关键字（总有人发小广告）

**Comment by guoyuanzhen321** [comment]
不知道现在是否已经解决了。
1. 收到评论以后做一个简单的string.replace(keyword, "*")行不行呢？
2. 查到了这两个网页：http://cwoebker.com/posts/the-beauty-of-big-pictures
                                    http://cwoebker.com/posts/the-beauty-of-python-crawling-1
不知道有没有用，但是哥们加油！:D

**Comment by yuadsl3010** [comment]
2015/5/25:评论这个已经完成了呢，目前还有图片需要实现

好勒，我回去瞧一瞧，谢啦！
