### ISSUE TITLE
【新需求】爬虫抓取图片的功能

### ISSUE THREAD

**Issue by yuadsl3010** [yuadsl3010/Delete-So#5]
这个功能应该实现在方法analyse里面：
1、为每条包含图片的评论打上一个标记，类似于删除和司机的标记
2、将该图片保存下来（放在服务器上）

tips：用正则表达式过滤识别图片应该蛮快的

**Comment by haoli001** [comment]
服务器的路径是什么样的呢？

**Comment by yuadsl3010** [comment]
如果要实现这个需求，首先看一看表的组成accomments（delete和siji表结构和accomments一致）和info表，分别对应评论和评论所在的投稿信息：
![_all](https://cloud.githubusercontent.com/assets/4989479/7902587/cf0debb2-07f0-11e5-8741-4e958d78faf5.PNG)
![accomments](https://cloud.githubusercontent.com/assets/4989479/7902588/d4973098-07f0-11e5-9590-9efc3e189a97.PNG)
![accommentsinfo](https://cloud.githubusercontent.com/assets/4989479/7902590/d8611324-07f0-11e5-9e8b-2bcd9f9b7c2f.PNG)

在本地构建好这4张表，就可以将spider跑起来了。
服务器是Ubuntu的，本地调通了之后再上服务器吧。

**Comment by haoli001** [comment]
请问一下spider用的是python2还是python3？
![2015-06-01 11 29 02](https://cloud.githubusercontent.com/assets/5494761/7905786/84a274a6-0851-11e5-954b-baf677b827f2.png)
启动main.py的时候报这个错是python版本的问题吗？

**Comment by yuadsl3010** [comment]
是python2.7的
这个问题应该是版本问题，python2和3几乎是两个语言

发自我的 iPhone

**Comment by haoli001** [comment]
QAQ我用的也是python2.7，那我换到ubuntu部署一下看看

**Comment by yuadsl3010** [comment]
不太可能呀，我晚上回去确认一下提交的代码是不是有问题

发自我的 iPhone

**Comment by yuadsl3010** [comment]
我在本地试了试，没有这个问题，是不是setting.ini里面动了什么设置？
或者自己调一调代码吧

**Comment by haoli001** [comment]
哦这样呀，我确实修改了setting.ini里面的设置

难道是因为修改了type类型的原因吗？这个链接本地的数据库有什么地方不对吗？

**Comment by yuadsl3010** [comment]
是的，type设置为1就OK了
要是还有其他的疑问，就加我QQ吧：315282945

**Comment by yuadsl3010** [comment]
这个需求关闭，没啥必要哈
